### ISSUE TITLE
[bug]: Plugin Does Not Exist - index.js

### ISSUE THREAD

**Issue by JJoTech** [magicoflolis/SquadJS-Watchdog#1]
### Describe the Bug

When following the Pre-requirements for installing this plugin, changing the index.js causes squadjs to crash on load. 

```
Error: Plugin WatchdogBase does not exist.
    at SquadServerFactory.buildFromConfig (file:///home/amp/.ampdata/instances/plugins/squad/SquadJS-4.2.0/squad-server/factory.js:48:15)
    at async main (file:///home/amp/.ampdata/instances/plugins/squad/SquadJS-4.2.0/index.js:14:7)
```

This is with the following changes inside the index.js file:

```
const pluginFilenames = [];
    for await (const dirent of dir) {
      // Check for non .js file type
      if (!dirent.isFile() || !dirent.name.endsWith('.js')) {
        continue;
      }
      if (
        [
          'index.js',
          'base-plugin.js',
          'watchdog-base-plugin.js',
          'discord-base-message-updater.js',
          'discord-base-plugin.js',
          'readme.md'
        ].includes(dirent.name)
      )
        continue;
      pluginFilenames.push(dirent.name);
    }
```

Removing the watchdog-base-plugin.js plugin from index.js allows SquadJS to load correctly although now with errors from Watchdog. 

```
[WatchdogBase][Error][1] [loadChannels] Could not fetch Discord channel "1266010202679935200", "id" must be a typeof String
[WatchdogBase][Error][1] Error: "id" must be a typeof String
    at WatchdogBase.fetchChannels (file:///home/amp/.ampdata/instances/plugins/squad/SquadJS-4.2.0/squad-server/plugins/watchdog-base-plugin.js:229:19)
    at WatchdogBase.prepareToMount (file:///home/amp/.ampdata/instances/plugins/squad/SquadJS-4.2.0/squad-server/plugins/watchdog-base-plugin.js:204:16)
    at SquadServerFactory.buildFromConfig (file:///home/amp/.ampdata/instances/plugins/squad/SquadJS-4.2.0/squad-server/factory.js:94:20)
    at async main (file:///home/amp/.ampdata/instances/plugins/squad/SquadJS-4.2.0/index.js:14:7)
[WatchdogBase][Log][1] Discord channels loaded: 0
```

I'm uncertain if the rest of the plugin is working correctly but it does not seem to identify the discord channel, does it not hook into squadjs for discord access?

**Comment by magicoflolis** [comment]
The file name is `Watchdog-base-plugin.js` with a capital **W**

```js
    const pluginFilenames = [];
    for await (const dirent of dir) {
      // Check for non .js file type
      if (!dirent.isFile() || !dirent.name.endsWith('.js')) {
        continue;
      }
      if (
        [
          'index.js',
          'base-plugin.js',
          'Watchdog-base-plugin.js',
          'discord-base-message-updater.js',
          'discord-base-plugin.js',
          'readme.md'
        ].includes(dirent.name)
      )
        continue;
      pluginFilenames.push(dirent.name);
    }
```

**Comment by JJoTech** [comment]
I have changed the capitalization of the file, although this does not fix the issue I am facing. You state that the base plugin needs to be excluded from loading via the index.js file. Adding the the Watchdog-base-plugin.js to the index file does not allow your plugin to load, SquadJS crashes on startup due to not finding the plugin. 
```
file:///home/amp/.ampdata/instances/plugins/squad/SquadJS-4.2.0/squad-server/factory.js:48
        throw new Error(`Plugin ${pluginConfig.plugin} does not exist.`);
              ^

Error: Plugin WatchdogBase does not exist.
    at SquadServerFactory.buildFromConfig (file:///home/amp/.ampdata/instances/plugins/squad/SquadJS-4.2.0/squad-server/factory.js:48:15)
    at async main (file:///home/amp/.ampdata/instances/plugins/squad/SquadJS-4.2.0/index.js:14:7)
```

How am I supposed to load your plugin if it is excluded on startup?

**Comment by magicoflolis** [comment]
I see the misunderstanding now, the [Watchdog-base-plugin.js](https://github.com/magicoflolis/SquadJS-Watchdog/blob/main/squad-server/plugins/Watchdog-base-plugin.js) acts as a "base plugin" similar to the [discord-base-plugin.js](https://github.com/magicoflolis/SquadJS/blob/master/squad-server/plugins/discord-base-plugin.js) for SquadJS.

**This means the plugin file should not be loaded directly, but should instead be used to "extend" other plugins!**
*For example, the [Watchdog-Cerberus.js](https://github.com/magicoflolis/SquadJS-Watchdog/blob/main/squad-server/plugins/Watchdog-Cerberus.js) plugin or the [Watchdog-Molly.js](https://github.com/magicoflolis/SquadJS-Watchdog/blob/main/squad-server/plugins/Watchdog-Molly.js) plugin OR any other custom plugins that require  [Watchdog-base-plugin.js](https://github.com/magicoflolis/SquadJS-Watchdog/blob/main/squad-server/plugins/Watchdog-base-plugin.js).*

I wrote it this way so that other plugin developers may create there own "watchdogs" *and because it is easier to work and write code with.*

Here is an example of how the plugin should be used.


> In SquadJS --> squad-server --> plugins
- Watchdog-base-plugin.js
- Watchdog-Cerberus.js (this is our "watchdog" plugin)

> Add "Cerberus" to the `config.json` and set a `channelID` for it to use in Discord.
```JSON
{
  "plugins": [{
      "plugin": "Cerberus",
      "enabled": true,
      "discordClient": "discord",
      "action": "none",
      "channelIDs": [
        "Valid Channel ID"
      ],
      "playerNames": {
        "action": "none",
        "alphabet": "abcdefghijklmnopqrstuvwxyz1234567890",
        "extends": "",
        "minimum": 0
      },
      "profanity": []
    }
  ]
}
```

You can read and learn more about what each option does [here](https://github.com/magicoflolis/SquadJS-Watchdog?tab=readme-ov-file#watchdog)

**Comment by JJoTech** [comment]
What you've said makes sense, I have added the base plugin to the index file and added Cerberus into my config and it seems to be working as intended. Thank you for explaining the setup to me!
